### PR TITLE
Close resource InputStream after use

### PR DESCRIPTION
**Pull request by gaul**

### CODE REVIEW

**Comment by andrewgaul** [comment]
@martylamb bump

**Comment by sbalabanov** [comment]
Closing all pull requests older than 6 months; please reopen if it is still relevant

**Comment by gaul** [comment]
I lack the karma to reopen this issue but I rebased the pull request.

**Comment by sbalabanov** [comment]
Once again it does not allow to reopen on forced push.
Notes if you want new PR:
- Class `Utils` is redundant, user try-with-resources instead, it handles null properly
- Format the code with google-style formatter

**Pull request closed without merging**
