### PR TITLE
Add support for -D (system properties) and -classpath flags

### PR DESCRIPTION
**Pull request by smvv**
Whitespace issues (trailing whitespaces, mixed hard tabs and spaces) are also fixed.

### CODE REVIEW

**Comment by sbalabanov** [comment]
Closing all pull requests older than 6 months; please reopen if it is still relevant

**Comment by cvogt** [comment]
This is an interesting PR in that it allows passing system properties from client to server. Especially nailgun agnostic programs run via nailgun sometimes require that in order to run at all. However this can easily leads to issues as system properties are global on the server between all threads not just the one triggered by the current nailgun invocation. So it may affect behavior of unrelated threads. One might argue that's fine since this feature enables some use cases that are currently prevented. But one might also argue that it's confusing and people should rather write their own alternative nailgun aware launchers if they want system properties. I tend to think it would probably be good to have this feature and try to help users not run into the pitfall while supporting it. I certainly would have used it in the past.

**Comment by sbalabanov** [comment]
I feel these use cases are too specific to deserve to be a part of nailgun communication protocol

**Comment by cvogt** [comment]
To me system properties seem similar to environment variables, which are already part of the protocol. I am more concerned about accidental misuse. But one could make the same argument about environment variables. So if they'd be handled in the same way, it would be most consistent I think.

**Pull request closed without merging**
