### PR TITLE
Add new Scala client implementation to README

### PR DESCRIPTION
**Pull request by jvican**

### CODE REVIEW

**Comment by jvican** [comment]
Mind having a look @sbalabanov ? It's a small README update to redirect people interested in a JVM library/binary for nailgun.

**Comment by jvican** [comment]
ping @sbalabanov :smile:

**Comment by jvican** [comment]
@philipjameson Could you have a quick look at this PR updating the docs? Thanks in advance!

**Comment by sbalabanov** [comment]
LGTM but I lost the permissions to merge :)

**Comment by philipjameson** [comment]
Looks good. Thanks!

**Comment by philipjameson** [comment]
Actually, those probably don't need to be numbered lists. Mind changing that back to unordered lists?

**Comment by jvican** [comment]
@philipjameson Done :smile:

**Pull request merged**
