### PR TITLE
try to fix race condition causing exit code 227

### PR DESCRIPTION
**Pull request by dwightguth**
Whenever I tried to run nailgun, I would always see intermittent socket disconnects causing the client to return error code 227 before it had finished printing everything to stdout/stderr. After I made this modification to the code, those went away. I believe what is happening is that socket.close does not wait for all the data to be sent to the client before breaking the connection.

### CODE REVIEW

**Comment by sdwilsh** [comment]
@dwightguth, would you be interested in addressing the merge conflicts and updating it so we can try to get this in?

**Comment by dwightguth** [comment]
I have not tested this yet, but I believe the merged version should address your issues.

**Comment by benhyland** [comment]
Note that we are still seeing 227 errors with buckd/nailgun even after facebook/buck#262 was closed. They are much less frequent, but I wonder if they might go away entirely if this got merged? I haven't been able to diagnose any further, as yet.

**Comment by dwightguth** [comment]
I suggest closing this in favor of #74 because it contains a more up-to-date fix.

**Comment by sbalabanov** [comment]
Closing all pull requests older than 6 months; please reopen if it is still relevant

**Pull request closed without merging**
