### PR TITLE
Fix data races

### PR DESCRIPTION
**Pull request by yilongli**
The changes are small. Please review. Thanks!

### CODE REVIEW

**Comment by denji** [comment]
Thanks for the patches, placed in the fork https://github.com/closure-gun/nailgun/compare/706de2e17104ddbfaa419003a3e0e15539df1e98...master

**Comment by yilongli** [comment]
@denji I think you missed the last one.

**Comment by denji** [comment]
@yilongli NGSessionPool removed my branch.

**Comment by jvican** [comment]
@styurin Since #1610 is closed, this should be closed too :wink:.

**Pull request closed without merging**
